
<!DOCTYPE html>

<html lang="es">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" /><meta name="generator" content="Docutils 0.17.1: http://docutils.sourceforge.net/" />
<meta property="og:title" content="Excepciones incorporadas" />
<meta property="og:type" content="website" />
<meta property="og:url" content="https://docs.python.org/3/library/exceptions.html" />
<meta property="og:site_name" content="Python documentation" />
<meta property="og:description" content="En Python, todas las excepciones deben ser instancias de una clase que se derive de BaseException. En una instrucción try con una cláusula except que menciona una clase determinada, esa cláusula ta..." />
<meta property="og:image" content="https://docs.python.org/3/_static/og-image.png" />
<meta property="og:image:alt" content="Python documentation" />
<meta name="description" content="En Python, todas las excepciones deben ser instancias de una clase que se derive de BaseException. En una instrucción try con una cláusula except que menciona una clase determinada, esa cláusula ta..." />
<meta property="og:image:width" content="200" />
<meta property="og:image:height" content="200" />
<meta name="theme-color" content="#3776ab" />

    <title>Excepciones incorporadas &#8212; documentación de Python - 3.11.2</title><meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" type="text/css" href="../_static/pygments.css" />
    <link rel="stylesheet" type="text/css" href="../_static/pydoctheme.css?digest=2d3badd06fe70b34b68db01f99471ce1624ffe4a" />
    
    <script data-url_root="../" id="documentation_options" src="../_static/documentation_options.js"></script>
    <script src="../_static/jquery.js"></script>
    <script src="../_static/underscore.js"></script>
    <script src="../_static/doctools.js"></script>
    <script src="../_static/translations.js"></script>
    
    <script src="../_static/sidebar.js"></script>
    
    <link rel="search" type="application/opensearchdescription+xml"
          title="Buscar en documentación de Python - 3.11.2"
          href="../_static/opensearch.xml"/>
    <link rel="author" title="Sobre este documento" href="../about.html" />
    <link rel="index" title="Índice" href="../genindex.html" />
    <link rel="search" title="Búsqueda" href="../search.html" />
    <link rel="copyright" title="Copyright" href="../copyright.html" />
    <link rel="next" title="Servicios de procesamiento de texto" href="text.html" />
    <link rel="prev" title="Tipos integrados" href="stdtypes.html" />
    <link rel="canonical" href="https://docs.python.org/3/library/exceptions.html" />
    
      
    

    
    <style>
      @media only screen {
        table.full-width-table {
            width: 100%;
        }
      }
    </style>
<link rel="shortcut icon" type="image/png" href="../_static/py.svg" />
            <script type="text/javascript" src="../_static/copybutton.js"></script>
            <script type="text/javascript" src="../_static/menu.js"></script> 

  </head>
<body>
<div class="mobile-nav">
    <input type="checkbox" id="menuToggler" class="toggler__input" aria-controls="navigation"
           aria-pressed="false" aria-expanded="false" role="button" aria-label="Menu" />
    <label for="menuToggler" class="toggler__label">
        <span></span>
    </label>
    <nav class="nav-content" role="navigation">
         <a href="https://www.python.org/" class="nav-logo">
             <img src="../_static/py.svg" alt="Logo"/>
         </a>
        <div class="version_switcher_placeholder"></div>
        <form role="search" class="search" action="../search.html" method="get">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" class="search-icon">
                <path fill-rule="nonzero"
                        d="M15.5 14h-.79l-.28-.27a6.5 6.5 0 001.48-5.34c-.47-2.78-2.79-5-5.59-5.34a6.505 6.505 0 00-7.27 7.27c.34 2.8 2.56 5.12 5.34 5.59a6.5 6.5 0 005.34-1.48l.27.28v.79l4.25 4.25c.41.41 1.08.41 1.49 0 .41-.41.41-1.08 0-1.49L15.5 14zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z" fill="#444"></path>
            </svg>
            <input type="text" name="q" aria-label="Búsqueda rápida"/>
            <input type="submit" value="Ir"/>
        </form>
    </nav>
    <div class="menu-wrapper">
        <nav class="menu" role="navigation" aria-label="main navigation">
            <div class="language_switcher_placeholder"></div>
  <div>
    <h3><a href="../contents.html">Tabla de contenido</a></h3>
    <ul>
<li><a class="reference internal" href="#">Excepciones incorporadas</a><ul>
<li><a class="reference internal" href="#exception-context">Contexto de una excepción</a></li>
<li><a class="reference internal" href="#inheriting-from-built-in-exceptions">Heredando de excepciones incorporadas</a></li>
<li><a class="reference internal" href="#base-classes">Clases base</a></li>
<li><a class="reference internal" href="#concrete-exceptions">Excepciones específicas</a><ul>
<li><a class="reference internal" href="#os-exceptions">Excepciones del sistema operativo</a></li>
</ul>
</li>
<li><a class="reference internal" href="#warnings">Advertencias</a></li>
<li><a class="reference internal" href="#exception-groups">Grupos de excepciones</a></li>
<li><a class="reference internal" href="#exception-hierarchy">Jerarquía de excepción</a></li>
</ul>
</li>
</ul>

  </div>
  <div>
    <h4>Tema anterior</h4>
    <p class="topless"><a href="stdtypes.html"
                          title="capítulo anterior">Tipos integrados</a></p>
  </div>
  <div>
    <h4>Próximo tema</h4>
    <p class="topless"><a href="text.html"
                          title="próximo capítulo">Servicios de procesamiento de texto</a></p>
  </div>
  <div role="note" aria-label="source link">
    <h3>Esta página</h3>
    <ul class="this-page-menu">
      <li><a href="../bugs.html">Reporta un bug</a></li>
      <li>
        <a href="https://github.com/python/cpython/blob/3.11/Doc/library/exceptions.rst"
            rel="nofollow">Ver fuente
        </a>
      </li>
    </ul>
  </div>
        </nav>
    </div>
</div>

  
    <div class="related" role="navigation" aria-label="related navigation">
      <h3>Navegación</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="../genindex.html" title="Índice general"
             accesskey="I">índice</a></li>
        <li class="right" >
          <a href="../py-modindex.html" title="Índice de Módulos Python"
             >módulos</a> |</li>
        <li class="right" >
          <a href="text.html" title="Servicios de procesamiento de texto"
             accesskey="N">siguiente</a> |</li>
        <li class="right" >
          <a href="stdtypes.html" title="Tipos integrados"
             accesskey="P">anterior</a> |</li>

          <li><img src="../_static/py.svg" alt="python logo" style="vertical-align: middle; margin-top: -1px"/></li>
          <li><a href="https://www.python.org/">Python</a> &#187;</li>
          <li class="switchers">
            <div class="language_switcher_placeholder"></div>
            <div class="version_switcher_placeholder"></div>
          </li>
          <li>
              
          </li>
    <li id="cpython-language-and-version">
      <a href="../index.html">3.11.2 Documentation</a> &#187;
    </li>

          <li class="nav-item nav-item-1"><a href="index.html" accesskey="U">La biblioteca estándar de Python</a> &#187;</li>
        <li class="nav-item nav-item-this"><a href="">Excepciones incorporadas</a></li>
                <li class="right">
                    

    <div class="inline-search" role="search">
        <form class="inline-search" action="../search.html" method="get">
          <input placeholder="Búsqueda rápida" aria-label="Búsqueda rápida" type="text" name="q" />
          <input type="submit" value="Ir" />
          <input type="hidden" name="check_keywords" value="yes" />
          <input type="hidden" name="area" value="default" />
        </form>
    </div>
                     |
                </li>
            
      </ul>
    </div>    

    <div class="document">
      <div class="documentwrapper">
        <div class="bodywrapper">
          <div class="body" role="main">
            
  <section id="built-in-exceptions">
<span id="bltin-exceptions"></span><h1>Excepciones incorporadas<a class="headerlink" href="#built-in-exceptions" title="Enlazar permanentemente con este título">¶</a></h1>
<p id="index-0">En Python, todas las excepciones deben ser instancias de una clase que se derive de <a class="reference internal" href="#BaseException" title="BaseException"><code class="xref py py-class docutils literal notranslate"><span class="pre">BaseException</span></code></a>. En una instrucción <a class="reference internal" href="../reference/compound_stmts.html#try"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">try</span></code></a> con una cláusula <a class="reference internal" href="../reference/compound_stmts.html#except"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">except</span></code></a> que menciona una clase determinada, esa cláusula también controla las clases de excepción derivadas de esa clase (excepto las clases de excepción de las que se deriva <em>it</em>). Dos clases de excepción que no están relacionadas mediante subclases nunca son equivalentes, incluso si tienen el mismo nombre.</p>
<p id="index-1">Las excepciones predefinidas enumeradas a continuación pueden ser generadas por el intérprete o funciones predefinidas. Excepto donde se mencione lo contrario, tienen un <em>associated value</em> que indica la causa detallada del error. Esto podría una cadena de caracteres o una tupla elementos con grandes elementos de información (por ejemplo, un código de error y una cadena que explica el código). El valor asociado generalmente se pasa como argumentos al constructor de la clase de excepción.</p>
<p>El código de usuario puede lanzar excepciones predefinidas. Esto puede ser usado para probar un gestor de excepciones o para notificar una condición de error «igual» a la situación en la cual el intérprete lance la misma excepción; pero tenga en cuenta que no hay nada que impida que el código del usuario produzca un error inapropiado.</p>
<p>Las clases de excepción predefinidas pueden ser usadas como subclases para definir otras nuevas; se recomienda a los programadores que deriven nuevas excepciones a partir de la clase <a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal notranslate"><span class="pre">Exception</span></code></a> o de una de sus subclases, y no de <a class="reference internal" href="#BaseException" title="BaseException"><code class="xref py py-exc docutils literal notranslate"><span class="pre">BaseException</span></code></a>. Hay disponible más información sobre la definición de excepciones en el Tutorial de Python en <a class="reference internal" href="../tutorial/errors.html#tut-userexceptions"><span class="std std-ref">Excepciones definidas por el usuario</span></a>.</p>
<section id="exception-context">
<h2>Contexto de una excepción<a class="headerlink" href="#exception-context" title="Enlazar permanentemente con este título">¶</a></h2>
<p>Al lanzar una nueva excepción mientras otra excepción está siendo manejada, el atributo <code class="xref py py-attr docutils literal notranslate"><span class="pre">__context__</span></code> de la nueva excepción es automáticamente asignado a la excepción manejada.  Una excepción puede ser manejada cuando se utiliza la cláusula <a class="reference internal" href="../reference/compound_stmts.html#except"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">except</span></code></a> o <a class="reference internal" href="../reference/compound_stmts.html#finally"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">finally</span></code></a>, o con la sentencia <a class="reference internal" href="../reference/compound_stmts.html#with"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">with</span></code></a>.</p>
<p>Este contexto de excepción implícita se puede complementar con una causa explícita usando <code class="xref std std-keyword docutils literal notranslate"><span class="pre">from</span></code> con <a class="reference internal" href="../reference/simple_stmts.html#raise"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">raise</span></code></a>:</p>
<div class="highlight-python3 notranslate"><div class="highlight"><pre><span></span><span class="k">raise</span> <span class="n">new_exc</span> <span class="kn">from</span> <span class="nn">original_exc</span>
</pre></div>
</div>
<p>La expresión que sigue a <a class="reference internal" href="../reference/simple_stmts.html#raise"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">from</span></code></a> debe ser una excepción o <code class="docutils literal notranslate"><span class="pre">None</span></code>. Se establecerá como <code class="xref py py-attr docutils literal notranslate"><span class="pre">__cause__</span></code> en la excepción generada. La configuración de <code class="xref py py-attr docutils literal notranslate"><span class="pre">__cause__</span></code> también establece implícitamente el atributo <code class="xref py py-attr docutils literal notranslate"><span class="pre">__suppress_context__</span></code> en <code class="docutils literal notranslate"><span class="pre">True</span></code>, de modo que el uso de <code class="docutils literal notranslate"><span class="pre">raise</span> <span class="pre">new_exc</span> <span class="pre">from</span> <span class="pre">None</span></code> reemplaza efectivamente la excepción anterior con la nueva para fines de visualización (por ejemplo, conversión de <a class="reference internal" href="#KeyError" title="KeyError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">KeyError</span></code></a> a <a class="reference internal" href="#AttributeError" title="AttributeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">AttributeError</span></code></a>), dejando la excepción anterior disponible en <code class="xref py py-attr docutils literal notranslate"><span class="pre">__context__</span></code> para introspección durante la depuración.</p>
<p>La visualización por defecto de la traza de error muestra estas excepciones encadenadas además de la traza de la propia excepción. Siempre se muestra una excepción encadenada explícitamente en <code class="xref py py-attr docutils literal notranslate"><span class="pre">__cause__</span></code> cuando está presente. Una excepción implícitamente encadenada en <code class="xref py py-attr docutils literal notranslate"><span class="pre">__context__</span></code> solo se muestra si <code class="xref py py-attr docutils literal notranslate"><span class="pre">__cause__</span></code> es <a class="reference internal" href="constants.html#None" title="None"><code class="xref py py-const docutils literal notranslate"><span class="pre">None</span></code></a> y <code class="xref py py-attr docutils literal notranslate"><span class="pre">__suppress_context__</span></code> es falso.</p>
<p>En cualquier caso, la excepción en sí siempre se muestra después de cualquier excepción encadenada para que la línea final del seguimiento siempre muestre la última excepción que se generó.</p>
</section>
<section id="inheriting-from-built-in-exceptions">
<h2>Heredando de excepciones incorporadas<a class="headerlink" href="#inheriting-from-built-in-exceptions" title="Enlazar permanentemente con este título">¶</a></h2>
<p>El código del usuario puede crear subclases que heredan de una excepción. Se recomienda heredar solo de una clase de tipo excepción a la vez para evitar cualquier conflicto posible en el manejo del atributo <code class="docutils literal notranslate"><span class="pre">args</span></code> por parte de las clases base, como también por posibles incompatibilidades en de la memoria.</p>
<div class="impl-detail compound">
<p><strong>Detalles de implementación de CPython:</strong> La mayoría de las excepciones integradas están implementadas en C por eficiencia, vea: <a class="reference external" href="https://github.com/python/cpython/tree/3.11/Objects/exceptions.c">Objects/exceptions.c</a>.  Algunas tienen distribuciones de memoria personalizadas, lo que hace imposible crear una subclase que herede de múltiples tipos de excepciones. La distribución de memoria de un tipo es un detalle de implementación y podría cambiar entre versiones de Python, llevando a nuevos conflictos en el futuro.  Por lo tanto, se recomienda evitar la herencia de múltiples tipos de excepción.</p>
</div>
</section>
<section id="base-classes">
<h2>Clases base<a class="headerlink" href="#base-classes" title="Enlazar permanentemente con este título">¶</a></h2>
<p>Las siguientes excepciones se utilizan principalmente como clases base para otras excepciones.</p>
<dl class="py exception">
<dt class="sig sig-object py" id="BaseException">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">BaseException</span></span><a class="headerlink" href="#BaseException" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>La clase base para todas las excepciones predefinidas. No está pensada para ser heredada directamente por las clases definidas por el usuario (para eso, use <a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal notranslate"><span class="pre">Exception</span></code></a>). Si se llama a <a class="reference internal" href="stdtypes.html#str" title="str"><code class="xref py py-func docutils literal notranslate"><span class="pre">str()</span></code></a> en una instancia de esta clase, se retorna la representación de los argumentos de la instancia o la cadena vacía cuando no había argumentos.</p>
<dl class="py attribute">
<dt class="sig sig-object py" id="BaseException.args">
<span class="sig-name descname"><span class="pre">args</span></span><a class="headerlink" href="#BaseException.args" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>La tupla de argumentos dada al constructor de excepción. Algunas excepciones predefinidas (como <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">OSError</span></code></a>) esperan un cierto número de argumentos y asignan un significado especial a los elementos de esta tupla, mientras que otras normalmente se llaman solo con una sola cadena que da un mensaje de error.</p>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="BaseException.with_traceback">
<span class="sig-name descname"><span class="pre">with_traceback</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">tb</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#BaseException.with_traceback" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Este método establece <em>tb</em> como el nuevo rastreo para la excepción y retorna el objeto de excepción. Se usaba con más frecuencia antes de que las características de encadenamiento de excepciones de <span class="target" id="index-20"></span><a class="pep reference external" href="https://peps.python.org/pep-3134/"><strong>PEP 3134</strong></a> estuvieran disponibles. El siguiente ejemplo muestra cómo podemos convertir una instancia de <code class="docutils literal notranslate"><span class="pre">SomeException</span></code> en una instancia de <code class="docutils literal notranslate"><span class="pre">OtherException</span></code> mientras se conserva el rastreo. Una vez generado, el marco actual se inserta en el rastreo del <code class="docutils literal notranslate"><span class="pre">OtherException</span></code>, como habría sucedido con el rastreo del <code class="docutils literal notranslate"><span class="pre">SomeException</span></code> original si hubiéramos permitido que se propagara al llamador.</p>
<div class="highlight-python3 notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="o">...</span>
<span class="k">except</span> <span class="n">SomeException</span><span class="p">:</span>
    <span class="n">tb</span> <span class="o">=</span> <span class="n">sys</span><span class="o">.</span><span class="n">exception</span><span class="p">()</span><span class="o">.</span><span class="n">__traceback__</span>
    <span class="k">raise</span> <span class="n">OtherException</span><span class="p">(</span><span class="o">...</span><span class="p">)</span><span class="o">.</span><span class="n">with_traceback</span><span class="p">(</span><span class="n">tb</span><span class="p">)</span>
</pre></div>
</div>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="BaseException.add_note">
<span class="sig-name descname"><span class="pre">add_note</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">note</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#BaseException.add_note" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Agrega la cadena <code class="docutils literal notranslate"><span class="pre">note</span></code> a las notas de la excepción, las cuales aparecen en el rastreo después de la cadena de la excepción. Se lanza un <a class="reference internal" href="#TypeError" title="TypeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">TypeError</span></code></a> si <code class="docutils literal notranslate"><span class="pre">note</span></code> no es una cadena de caracteres.</p>
<div class="versionadded">
<p><span class="versionmodified added">Nuevo en la versión 3.11.</span></p>
</div>
</dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="BaseException.__notes__">
<span class="sig-name descname"><span class="pre">__notes__</span></span><a class="headerlink" href="#BaseException.__notes__" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Una lista de las notas de esta excepción, las cuales fueron añadidas con el método <a class="reference internal" href="#BaseException.add_note" title="BaseException.add_note"><code class="xref py py-meth docutils literal notranslate"><span class="pre">add_note()</span></code></a>. Este atributo es creado cuando se llama a <a class="reference internal" href="#BaseException.add_note" title="BaseException.add_note"><code class="xref py py-meth docutils literal notranslate"><span class="pre">add_note()</span></code></a>.</p>
<div class="versionadded">
<p><span class="versionmodified added">Nuevo en la versión 3.11.</span></p>
</div>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="Exception">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">Exception</span></span><a class="headerlink" href="#Exception" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Todas las excepciones predefinidas <em>non-system-exiting</em>, que no salen del sistema se derivan de esta clase. Todas las excepciones definidas por el usuario también deben derivarse de esta clase.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="ArithmeticError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">ArithmeticError</span></span><a class="headerlink" href="#ArithmeticError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>La clase base para las excepciones predefinidas que se generan para varios errores aritméticos: <a class="reference internal" href="#OverflowError" title="OverflowError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">OverflowError</span></code></a>, <a class="reference internal" href="#ZeroDivisionError" title="ZeroDivisionError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ZeroDivisionError</span></code></a>, <a class="reference internal" href="#FloatingPointError" title="FloatingPointError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">FloatingPointError</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="BufferError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">BufferError</span></span><a class="headerlink" href="#BufferError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando <a class="reference internal" href="../c-api/buffer.html#bufferobjects"><span class="std std-ref">buffer</span></a> no se puede realizar una operación relacionada.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="LookupError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">LookupError</span></span><a class="headerlink" href="#LookupError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>La clase base para las excepciones que se generan cuando una clave o índice utilizado en un mapa o secuencia que no es válido: <a class="reference internal" href="#IndexError" title="IndexError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">IndexError</span></code></a>, <a class="reference internal" href="#KeyError" title="KeyError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">KeyError</span></code></a>. Esto se puede lanzar directamente por <a class="reference internal" href="codecs.html#codecs.lookup" title="codecs.lookup"><code class="xref py py-func docutils literal notranslate"><span class="pre">codecs.lookup()</span></code></a>.</p>
</dd></dl>

</section>
<section id="concrete-exceptions">
<h2>Excepciones específicas<a class="headerlink" href="#concrete-exceptions" title="Enlazar permanentemente con este título">¶</a></h2>
<p>Las siguientes excepciones son las excepciones que normalmente se generan.</p>
<dl class="py exception">
<dt class="sig sig-object py" id="AssertionError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">AssertionError</span></span><a class="headerlink" href="#AssertionError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p id="index-3">Se genera cuando se produce un error en una instrucción <a class="reference internal" href="../reference/simple_stmts.html#assert"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">assert</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="AttributeError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">AttributeError</span></span><a class="headerlink" href="#AttributeError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando se produce un error en una referencia de atributo (ver <a class="reference internal" href="../reference/expressions.html#attribute-references"><span class="std std-ref">Referencias de atributos</span></a>) o la asignación falla. (Cuando un objeto no admite referencias de atributos o asignaciones de atributos en absoluto, se genera <a class="reference internal" href="#TypeError" title="TypeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">TypeError</span></code></a>.)</p>
<p>Los atributos <code class="xref py py-attr docutils literal notranslate"><span class="pre">name</span></code> y <code class="xref py py-attr docutils literal notranslate"><span class="pre">obj</span></code> se pueden configurar utilizando argumentos de solo palabras clave para el constructor. Cuando se establecen, representan el nombre del atributo al que se intentó acceder y el objeto al que se accedió para dicho atributo, respectivamente.</p>
<div class="versionchanged">
<p><span class="versionmodified changed">Distinto en la versión 3.10: </span>Se agregaron los atributos <code class="xref py py-attr docutils literal notranslate"><span class="pre">name</span></code> y <code class="xref py py-attr docutils literal notranslate"><span class="pre">obj</span></code>.</p>
</div>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="EOFError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">EOFError</span></span><a class="headerlink" href="#EOFError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando la función <a class="reference internal" href="functions.html#input" title="input"><code class="xref py py-func docutils literal notranslate"><span class="pre">input()</span></code></a> alcanza una condición de fin de archivo (EOF) sin leer ningún dato. (Note que el <code class="xref py py-meth docutils literal notranslate"><span class="pre">io.</span> <span class="pre">IOBase.read()</span></code> y <a class="reference internal" href="io.html#io.IOBase.readline" title="io.IOBase.readline"><code class="xref py py-meth docutils literal notranslate"><span class="pre">io.IOBase.readline()</span></code></a> retornan una cadena vacía cuando llegan a EOF.)</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="FloatingPointError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">FloatingPointError</span></span><a class="headerlink" href="#FloatingPointError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>No se usa actualmente.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="GeneratorExit">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">GeneratorExit</span></span><a class="headerlink" href="#GeneratorExit" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando un <a class="reference internal" href="../glossary.html#term-generator"><span class="xref std std-term">generator</span></a> o <a class="reference internal" href="../glossary.html#term-coroutine"><span class="xref std std-term">coroutine</span></a> está cerrado; ver <a class="reference internal" href="../reference/expressions.html#generator.close" title="generator.close"><code class="xref py py-meth docutils literal notranslate"><span class="pre">generator.close()</span></code></a> y <a class="reference internal" href="../reference/datamodel.html#coroutine.close" title="coroutine.close"><code class="xref py py-meth docutils literal notranslate"><span class="pre">coroutine.close()</span></code></a>. Hereda directamente de <a class="reference internal" href="#BaseException" title="BaseException"><code class="xref py py-exc docutils literal notranslate"><span class="pre">BaseException</span></code></a> en lugar de <a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal notranslate"><span class="pre">Exception</span></code></a> ya que técnicamente no es un error.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="ImportError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">ImportError</span></span><a class="headerlink" href="#ImportError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando la instrucción <a class="reference internal" href="../reference/simple_stmts.html#import"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">import</span></code></a> tiene problemas al intentar cargar un módulo. También se produce cuando la <em>from list</em> en <code class="docutils literal notranslate"><span class="pre">from</span> <span class="pre">...</span> <span class="pre">import</span></code> tiene un nombre que no se puede encontrar.</p>
<p>Los atributos <code class="xref py py-attr docutils literal notranslate"><span class="pre">name</span></code> y <code class="xref py py-attr docutils literal notranslate"><span class="pre">path</span></code> solo se pueden establecer utilizando argumentos de palabra clave en el constructor. Cuando se establece, representan el nombre del módulo que se intentó importar y la ruta de acceso a cualquier archivo que desencadenó la excepción, respectivamente.</p>
<div class="versionchanged">
<p><span class="versionmodified changed">Distinto en la versión 3.3: </span>Se han añadido los atributos <code class="xref py py-attr docutils literal notranslate"><span class="pre">name</span></code> y <code class="xref py py-attr docutils literal notranslate"><span class="pre">path</span></code>.</p>
</div>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="ModuleNotFoundError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">ModuleNotFoundError</span></span><a class="headerlink" href="#ModuleNotFoundError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Una subclase de <a class="reference internal" href="#ImportError" title="ImportError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ImportError</span></code></a> que se genera mediante <a class="reference internal" href="../reference/simple_stmts.html#import"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">import</span></code></a> cuando no se pudo encontrar un módulo. También se genera cuando <code class="docutils literal notranslate"><span class="pre">None</span></code> se encuentra en <a class="reference internal" href="sys.html#sys.modules" title="sys.modules"><code class="xref py py-data docutils literal notranslate"><span class="pre">sys.modules</span></code></a>.</p>
<div class="versionadded">
<p><span class="versionmodified added">Nuevo en la versión 3.6.</span></p>
</div>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="IndexError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">IndexError</span></span><a class="headerlink" href="#IndexError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando un subíndice de secuencia está fuera del rango. (Los índices de la rebanada son truncados silenciosamente para caer en el intervalo permitido; si un índice no es un entero, se genera <a class="reference internal" href="#TypeError" title="TypeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">TypeError</span></code></a>.)</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="KeyError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">KeyError</span></span><a class="headerlink" href="#KeyError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando no se encuentra una clave de asignación (diccionario) en el conjunto de claves existentes (mapa).</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="KeyboardInterrupt">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">KeyboardInterrupt</span></span><a class="headerlink" href="#KeyboardInterrupt" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando el usuario pulsa la tecla de interrupción (normalmente <kbd class="kbd compound docutils literal notranslate"><kbd class="kbd docutils literal notranslate">Control</kbd>-<kbd class="kbd docutils literal notranslate">C</kbd></kbd> o <kbd class="kbd docutils literal notranslate">Delete</kbd>). Durante la ejecución, se realiza una comprobación de interrupciones con regularidad. La excepción hereda de <a class="reference internal" href="#BaseException" title="BaseException"><code class="xref py py-exc docutils literal notranslate"><span class="pre">BaseException</span></code></a> para no ser detectada de forma accidental por <a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal notranslate"><span class="pre">Exception</span></code></a> y, por lo tanto, prevenir que el intérprete salga.</p>
<div class="admonition note">
<p class="admonition-title">Nota</p>
<p>Capturar una <a class="reference internal" href="#KeyboardInterrupt" title="KeyboardInterrupt"><code class="xref py py-exc docutils literal notranslate"><span class="pre">KeyboardInterrupt</span></code></a> requiere especial consideración. Debido a que puede ser lanzada en puntos impredecibles, puede, en algunas circunstancias, dejar al programa en ejecución en un estado inconsistente. Por lo general, es mejor permitir que <a class="reference internal" href="#KeyboardInterrupt" title="KeyboardInterrupt"><code class="xref py py-exc docutils literal notranslate"><span class="pre">KeyboardInterrupt</span></code></a> termine el programa tan pronto como sea o evitar lanzarla por completo. (Vea <a class="reference internal" href="signal.html#handlers-and-exceptions"><span class="std std-ref">Note on Signal Handlers and Exceptions</span></a>.)</p>
</div>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="MemoryError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">MemoryError</span></span><a class="headerlink" href="#MemoryError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando una operación se queda sin memoria pero la situación aún puede ser recuperada (eliminando algunos objetos). El valor asociado es una cadena que indica que tipo de operación (interna) se quedó sin memoria. Tenga en cuenta que debido a la arquitectura de administración de memoria (función <code class="xref c c-func docutils literal notranslate"><span class="pre">malloc()</span></code> de C), el intérprete no siempre puede recuperarse completamente de esta situación; sin embargo, plantea una excepción para que se pueda imprimir un seguimiento de la pila, en caso de que un programa fuera de servicio fuera lo causa.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="NameError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">NameError</span></span><a class="headerlink" href="#NameError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando no se encuentra un nombre local o global. Esto se aplica solo a nombres no calificados. El valor asociado es un mensaje de error que incluye el nombre que no se pudo encontrar.</p>
<p>El atributo <code class="xref py py-attr docutils literal notranslate"><span class="pre">name</span></code> se puede establecer utilizando un argumento de solo palabra clave para el constructor. Cuando se establece, representa el nombre de la variable a la que se intentó acceder.</p>
<div class="versionchanged">
<p><span class="versionmodified changed">Distinto en la versión 3.10: </span>Se agregó el atributo <code class="xref py py-attr docutils literal notranslate"><span class="pre">name</span></code>.</p>
</div>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="NotImplementedError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">NotImplementedError</span></span><a class="headerlink" href="#NotImplementedError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Esta excepción se deriva de <a class="reference internal" href="#RuntimeError" title="RuntimeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">RuntimeError</span></code></a>. En las clases base definidas por el usuario, los métodos abstractos deberían lanzar esta excepción cuando requieren clases derivadas para anular el método, o mientras se desarrolla la clase para indicar que la implementación real aún necesita ser agregada.</p>
<div class="admonition note">
<p class="admonition-title">Nota</p>
<p>No debe usarse para indicar que un operador o método no debe ser admitido en absoluto – en ese caso, deje el operador / método sin definir o, si es una subclase, se establece en <a class="reference internal" href="constants.html#None" title="None"><code class="xref py py-data docutils literal notranslate"><span class="pre">None</span></code></a>.</p>
</div>
<div class="admonition note">
<p class="admonition-title">Nota</p>
<p><code class="docutils literal notranslate"><span class="pre">NotImplementedError</span></code> y <code class="docutils literal notranslate"><span class="pre">NotImplemented</span></code> no son intercambiables, a pesar de que tienen nombres y propósitos similares. Consulte <a class="reference internal" href="constants.html#NotImplemented" title="NotImplemented"><code class="xref py py-data docutils literal notranslate"><span class="pre">NotImplemented</span></code></a> para obtener detalles sobre cuándo usarlo.</p>
</div>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="OSError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">OSError</span></span><span class="sig-paren">(</span><span class="optional">[</span><em class="sig-param"><span class="n"><span class="pre">arg</span></span></em><span class="optional">]</span><span class="sig-paren">)</span><a class="headerlink" href="#OSError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dt class="sig sig-object py">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">OSError</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">errno</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">strerror</span></span></em><span class="optional">[</span>, <em class="sig-param"><span class="n"><span class="pre">filename</span></span></em><span class="optional">[</span>, <em class="sig-param"><span class="n"><span class="pre">winerror</span></span></em><span class="optional">[</span>, <em class="sig-param"><span class="n"><span class="pre">filename2</span></span></em><span class="optional">]</span><span class="optional">]</span><span class="optional">]</span><span class="sig-paren">)</span></dt>
<dd><p id="index-4">Esta excepción se produce cuando una función del sistema retorna un error relacionado con el sistema, que incluye fallas de E/S como <code class="docutils literal notranslate"><span class="pre">file</span> <span class="pre">not</span> <span class="pre">found</span></code> o <code class="docutils literal notranslate"><span class="pre">disk</span> <span class="pre">full</span></code> (no para tipos de argumentos ilegales u otros errores incidentales).</p>
<p>La segunda forma del constructor establece los atributos correspondientes, que se describen a continuación. Los atributos predeterminados son <a class="reference internal" href="constants.html#None" title="None"><code class="xref py py-const docutils literal notranslate"><span class="pre">None</span></code></a> si no se especifican. Para compatibilidad con versiones anteriores, si se pasan tres argumentos, el atributo <a class="reference internal" href="#BaseException.args" title="BaseException.args"><code class="xref py py-attr docutils literal notranslate"><span class="pre">args</span></code></a> contiene solo una tupla de 2 de los dos primeros argumentos del constructor.</p>
<p>El constructor a menudo retorna una subclase de <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">OSError</span></code></a>, como se describe en <a class="reference internal" href="#os-exceptions">OS exceptions</a> a continuación. La subclase particular depende del valor final <a class="reference internal" href="#OSError.errno" title="OSError.errno"><code class="xref py py-attr docutils literal notranslate"><span class="pre">errno</span></code></a>. Este comportamiento solo ocurre cuando se construye <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">OSError</span></code></a> directamente o mediante un alias, y no se hereda al derivar.</p>
<dl class="py attribute">
<dt class="sig sig-object py" id="OSError.errno">
<span class="sig-name descname"><span class="pre">errno</span></span><a class="headerlink" href="#OSError.errno" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Un código de error numérico de la variable C, <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code>.</p>
</dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="OSError.winerror">
<span class="sig-name descname"><span class="pre">winerror</span></span><a class="headerlink" href="#OSError.winerror" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>En Windows, esto le proporciona el código de error nativo de Windows. El atributo <a class="reference internal" href="#OSError.errno" title="OSError.errno"><code class="xref py py-attr docutils literal notranslate"><span class="pre">errno</span></code></a> es entonces una traducción aproximada, en términos POSIX, de ese código de error nativo.</p>
<p>En Windows, si el argumento del constructor <code class="docutils literal notranslate"><span class="pre">winerror</span></code> es un entero, el atributo <a class="reference internal" href="#OSError.errno" title="OSError.errno"><code class="xref py py-attr docutils literal notranslate"><span class="pre">errno</span></code></a> se determina a partir del código de error de Windows y el argumento <code class="docutils literal notranslate"><span class="pre">errno</span></code> se ignora. En otras plataformas, el argumento <code class="docutils literal notranslate"><span class="pre">winerror</span></code> se ignora y el atributo <a class="reference internal" href="#OSError.winerror" title="OSError.winerror"><code class="xref py py-attr docutils literal notranslate"><span class="pre">winerror</span></code></a> no existe.</p>
</dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="OSError.strerror">
<span class="sig-name descname"><span class="pre">strerror</span></span><a class="headerlink" href="#OSError.strerror" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>El mensaje de error correspondiente, tal como lo proporciona el sistema operativo. Está formateado por las funciones de C, <code class="xref c c-func docutils literal notranslate"><span class="pre">perror()</span></code> en POSIX, y <code class="xref c c-func docutils literal notranslate"><span class="pre">FormatMessage()</span></code> en Windows.</p>
</dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="OSError.filename">
<span class="sig-name descname"><span class="pre">filename</span></span><a class="headerlink" href="#OSError.filename" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dt class="sig sig-object py" id="OSError.filename2">
<span class="sig-name descname"><span class="pre">filename2</span></span><a class="headerlink" href="#OSError.filename2" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Para las excepciones que involucran una ruta del sistema de archivos (como <a class="reference internal" href="functions.html#open" title="open"><code class="xref py py-func docutils literal notranslate"><span class="pre">open()</span></code></a> o <a class="reference internal" href="os.html#os.unlink" title="os.unlink"><code class="xref py py-func docutils literal notranslate"><span class="pre">os.unlink()</span></code></a>), <a class="reference internal" href="#OSError.filename" title="OSError.filename"><code class="xref py py-attr docutils literal notranslate"><span class="pre">filename</span></code></a> es el nombre del archivo pasado a la función. Para las funciones que involucran dos rutas del sistema de archivos (como <a class="reference internal" href="os.html#os.rename" title="os.rename"><code class="xref py py-func docutils literal notranslate"><span class="pre">os.rename()</span></code></a>), <a class="reference internal" href="#OSError.filename2" title="OSError.filename2"><code class="xref py py-attr docutils literal notranslate"><span class="pre">filename2</span></code></a> corresponde al segundo nombre de archivo pasado a la función.</p>
</dd></dl>

<div class="versionchanged">
<p><span class="versionmodified changed">Distinto en la versión 3.3: </span><a class="reference internal" href="#EnvironmentError" title="EnvironmentError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">EnvironmentError</span></code></a>, <a class="reference internal" href="#IOError" title="IOError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">IOError</span></code></a>, <a class="reference internal" href="#WindowsError" title="WindowsError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">WindowsError</span></code></a>, <a class="reference internal" href="socket.html#socket.error" title="socket.error"><code class="xref py py-exc docutils literal notranslate"><span class="pre">socket.error</span></code></a>, <a class="reference internal" href="select.html#select.error" title="select.error"><code class="xref py py-exc docutils literal notranslate"><span class="pre">select.error</span></code></a> y <code class="xref py py-exc docutils literal notranslate"><span class="pre">mmap.error</span></code> se han fusionado en <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">OSError</span></code></a>, y el constructor puede retornar una subclase.</p>
</div>
<div class="versionchanged">
<p><span class="versionmodified changed">Distinto en la versión 3.4: </span>El atributo <a class="reference internal" href="#OSError.filename" title="OSError.filename"><code class="xref py py-attr docutils literal notranslate"><span class="pre">filename</span></code></a> es ahora el nombre de archivo original pasado a la función, en lugar del nombre codificado o decodificado desde <a class="reference internal" href="../glossary.html#term-filesystem-encoding-and-error-handler"><span class="xref std std-term">filesystem encoding and error handler</span></a>. Además, se agregaron el argumento y atributo del constructor <em>filename2</em>.</p>
</div>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="OverflowError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">OverflowError</span></span><a class="headerlink" href="#OverflowError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando el resultado de una operación aritmética es demasiado grande para ser representado. Esto no puede ocurrir para los enteros (para lo cual es mejor lanzar <a class="reference internal" href="#MemoryError" title="MemoryError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">MemoryError</span></code></a> que darse por vencido). Sin embargo, por razones históricas, <code class="docutils literal notranslate"><span class="pre">OverflowError</span></code> a veces se genera para enteros que están fuera del rango requerido. Debido a la falta de estandarización del manejo de excepciones de coma flotante en C, la mayoría de las operaciones de coma flotante no se verifican.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="RecursionError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">RecursionError</span></span><a class="headerlink" href="#RecursionError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Esta excepción se deriva de <a class="reference internal" href="#RuntimeError" title="RuntimeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">RuntimeError</span></code></a>. Se lanza cuando el intérprete detecta que se excede la profundidad máxima de recursión (ver <a class="reference internal" href="sys.html#sys.getrecursionlimit" title="sys.getrecursionlimit"><code class="xref py py-func docutils literal notranslate"><span class="pre">sys.getrecursionlimit()</span></code></a>).</p>
<div class="versionadded">
<p><span class="versionmodified added">Nuevo en la versión 3.5: </span>Anteriormente, se planteó un simple <a class="reference internal" href="#RuntimeError" title="RuntimeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">RuntimeError</span></code></a>.</p>
</div>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="ReferenceError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">ReferenceError</span></span><a class="headerlink" href="#ReferenceError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Esta excepción se produce cuando un proxy de referencia débil, creado por la función <a class="reference internal" href="weakref.html#weakref.proxy" title="weakref.proxy"><code class="xref py py-func docutils literal notranslate"><span class="pre">weakref.proxy()</span></code></a>, se utiliza para acceder a un atributo del referente después de que se ha recolectado basura. Para obtener más información sobre referencias débiles, consulte el módulo <a class="reference internal" href="weakref.html#module-weakref" title="weakref: Support for weak references and weak dictionaries."><code class="xref py py-mod docutils literal notranslate"><span class="pre">weakref</span></code></a> .</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="RuntimeError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">RuntimeError</span></span><a class="headerlink" href="#RuntimeError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando se detecta un error que no corresponde a ninguna de las otras categorías. El valor asociado es una cadena que indica exactamente qué salió mal.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="StopIteration">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">StopIteration</span></span><a class="headerlink" href="#StopIteration" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Generado por la función incorporada <a class="reference internal" href="functions.html#next" title="next"><code class="xref py py-func docutils literal notranslate"><span class="pre">next()</span></code></a> y un <a class="reference internal" href="../glossary.html#term-iterator"><span class="xref std std-term">iterator</span></a>'s <a class="reference internal" href="stdtypes.html#iterator.__next__" title="iterator.__next__"><code class="xref py py-meth docutils literal notranslate"><span class="pre">__next__()</span></code></a> para indicar que no hay más elementos producidos por el iterador.</p>
<p>El objeto de excepción tiene un solo atributo <code class="xref py py-attr docutils literal notranslate"><span class="pre">value</span></code>, que se proporciona como argumento al construir la excepción, y por defecto es <a class="reference internal" href="constants.html#None" title="None"><code class="xref py py-const docutils literal notranslate"><span class="pre">None</span></code></a>.</p>
<p>Cuando se retorna una función <a class="reference internal" href="../glossary.html#term-generator"><span class="xref std std-term">generator</span></a> o <a class="reference internal" href="../glossary.html#term-coroutine"><span class="xref std std-term">coroutine</span></a>, se genera una nueva instancia <a class="reference internal" href="#StopIteration" title="StopIteration"><code class="xref py py-exc docutils literal notranslate"><span class="pre">StopIteration</span></code></a>, y el valor retornado por la función se utiliza como parámetro <code class="xref py py-attr docutils literal notranslate"><span class="pre">value</span></code> para constructor de la excepción.</p>
<p>Si un generador lanza directa o indirectamente <a class="reference internal" href="#StopIteration" title="StopIteration"><code class="xref py py-exc docutils literal notranslate"><span class="pre">StopIteration</span></code></a>, se convierte en <a class="reference internal" href="#RuntimeError" title="RuntimeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">RuntimeError</span></code></a> (conservando <a class="reference internal" href="#StopIteration" title="StopIteration"><code class="xref py py-exc docutils literal notranslate"><span class="pre">StopIteration</span></code></a> como la causa de la nueva excepción).</p>
<div class="versionchanged">
<p><span class="versionmodified changed">Distinto en la versión 3.3: </span>Se agregó el atributo <cite>*value*</cite> y la capacidad de las funciones del generador de usarlo para retornar un valor.</p>
</div>
<div class="versionchanged">
<p><span class="versionmodified changed">Distinto en la versión 3.5: </span>Introdujo la transformación <em>RuntimeError</em> a través de <code class="docutils literal notranslate"><span class="pre">from</span> <span class="pre">__future__</span> <span class="pre">import</span> <span class="pre">generator_stop</span></code>, ver <span class="target" id="index-21"></span><a class="pep reference external" href="https://peps.python.org/pep-0479/"><strong>PEP 479</strong></a>.</p>
</div>
<div class="versionchanged">
<p><span class="versionmodified changed">Distinto en la versión 3.7: </span>Habilitar <span class="target" id="index-22"></span><a class="pep reference external" href="https://peps.python.org/pep-0479/"><strong>PEP 479</strong></a> para todo el código por defecto: a <a class="reference internal" href="#StopIteration" title="StopIteration"><code class="xref py py-exc docutils literal notranslate"><span class="pre">StopIteration</span></code></a> generado en un generador se transforma en <a class="reference internal" href="#RuntimeError" title="RuntimeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">RuntimeError</span></code></a>.</p>
</div>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="StopAsyncIteration">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">StopAsyncIteration</span></span><a class="headerlink" href="#StopAsyncIteration" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se debe lanzar mediante <code class="xref py py-meth docutils literal notranslate"><span class="pre">__anext__()</span></code> de un objeto <a class="reference internal" href="../glossary.html#term-asynchronous-iterator"><span class="xref std std-term">asynchronous iterator</span></a> para detener la iteración.</p>
<div class="versionadded">
<p><span class="versionmodified added">Nuevo en la versión 3.5.</span></p>
</div>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="SyntaxError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">SyntaxError</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">message</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">details</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#SyntaxError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando el analizador encuentra un error de sintaxis. Esto puede ocurrir en una instrucción <a class="reference internal" href="../reference/simple_stmts.html#import"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">import</span></code></a>, en una llamada a las funciones integradas <a class="reference internal" href="functions.html#compile" title="compile"><code class="xref py py-func docutils literal notranslate"><span class="pre">compile()</span></code></a>, <a class="reference internal" href="functions.html#exec" title="exec"><code class="xref py py-func docutils literal notranslate"><span class="pre">exec()</span></code></a> o <a class="reference internal" href="functions.html#eval" title="eval"><code class="xref py py-func docutils literal notranslate"><span class="pre">eval()</span></code></a>, o al leer el script inicial o la entrada estándar (también de forma interactiva).</p>
<p>El <a class="reference internal" href="stdtypes.html#str" title="str"><code class="xref py py-func docutils literal notranslate"><span class="pre">str()</span></code></a> de la instancia de excepción retorna solo el mensaje de error. Detalles es una tupla cuyos miembros también están disponibles como atributos separados.</p>
<dl class="py attribute">
<dt class="sig sig-object py" id="SyntaxError.filename">
<span class="sig-name descname"><span class="pre">filename</span></span><a class="headerlink" href="#SyntaxError.filename" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>El nombre del archivo en el que se produjo el error de sintaxis.</p>
</dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="SyntaxError.lineno">
<span class="sig-name descname"><span class="pre">lineno</span></span><a class="headerlink" href="#SyntaxError.lineno" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>En qué número de línea del archivo se produjo el error. Tiene un índice 1: la primera línea del archivo tiene un <code class="docutils literal notranslate"><span class="pre">lineno</span></code> de 1.</p>
</dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="SyntaxError.offset">
<span class="sig-name descname"><span class="pre">offset</span></span><a class="headerlink" href="#SyntaxError.offset" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>La columna de la línea donde ocurrió el error. Está indexado a 1: el primer carácter de la línea tiene un <code class="docutils literal notranslate"><span class="pre">offset</span></code> de 1.</p>
</dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="SyntaxError.text">
<span class="sig-name descname"><span class="pre">text</span></span><a class="headerlink" href="#SyntaxError.text" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>El texto del código fuente involucrado en el error.</p>
</dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="SyntaxError.end_lineno">
<span class="sig-name descname"><span class="pre">end_lineno</span></span><a class="headerlink" href="#SyntaxError.end_lineno" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>En qué número de línea del archivo termina el error. Está indexado a 1: la primera línea del archivo tiene un <code class="docutils literal notranslate"><span class="pre">lineno</span></code> de 1.</p>
</dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="SyntaxError.end_offset">
<span class="sig-name descname"><span class="pre">end_offset</span></span><a class="headerlink" href="#SyntaxError.end_offset" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Finaliza la columna de la línea final donde ocurrió el error. Está indexado a 1: el primer carácter de la línea tiene un <code class="docutils literal notranslate"><span class="pre">offset</span></code> de 1.</p>
</dd></dl>

<p>Para errores en los campos de cadena f, el mensaje tiene el prefijo «cadena f:» y las compensaciones son compensaciones en un texto construido a partir de la expresión de reemplazo. Por ejemplo, compilar f’Bad {ab} field “da como resultado este atributo args: (” f-string: … “, (” “, 1, 2,” (ab) n “, 1, 5)) .</p>
<div class="versionchanged">
<p><span class="versionmodified changed">Distinto en la versión 3.10: </span>Se agregaron los atributos <a class="reference internal" href="#SyntaxError.end_lineno" title="SyntaxError.end_lineno"><code class="xref py py-attr docutils literal notranslate"><span class="pre">end_lineno</span></code></a> y <a class="reference internal" href="#SyntaxError.end_offset" title="SyntaxError.end_offset"><code class="xref py py-attr docutils literal notranslate"><span class="pre">end_offset</span></code></a>.</p>
</div>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="IndentationError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">IndentationError</span></span><a class="headerlink" href="#IndentationError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Clase base para errores de sintaxis relacionados con sangría incorrecta. Esta es una subclase de <a class="reference internal" href="#SyntaxError" title="SyntaxError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">SyntaxError</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="TabError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">TabError</span></span><a class="headerlink" href="#TabError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando la sangría contiene un uso inconsistente de pestañas y espacios. Esta es una subclase de <a class="reference internal" href="#IndentationError" title="IndentationError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">IndentationError</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="SystemError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">SystemError</span></span><a class="headerlink" href="#SystemError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando el intérprete encuentra un error interno, pero la situación no parece tan grave como para abandonar toda esperanza. El valor asociado es una cadena que indica qué salió mal (a bajo nivel).</p>
<p>Debe informar esto al autor o responsable de su intérprete de Python. Asegúrese de informar la versión del intérprete de Python (<code class="docutils literal notranslate"><span class="pre">sys.version</span></code>; también se imprime al comienzo de una sesión interactiva de Python), el mensaje de error exacto (el valor asociado de la excepción) y, si es posible, la fuente del programa que activó el error.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="SystemExit">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">SystemExit</span></span><a class="headerlink" href="#SystemExit" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Esta excepción es provocada por la función <a class="reference internal" href="sys.html#sys.exit" title="sys.exit"><code class="xref py py-func docutils literal notranslate"><span class="pre">sys.exit()</span></code></a>. Hereda de <a class="reference internal" href="#BaseException" title="BaseException"><code class="xref py py-exc docutils literal notranslate"><span class="pre">BaseException</span></code></a> en lugar de <a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal notranslate"><span class="pre">Exception</span></code></a> para que no sea gestionada accidentalmente por el código que captura <a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal notranslate"><span class="pre">Exception</span></code></a>. Esto permite que la excepción se propague correctamente y que el intérprete salga. Cuando no se maneja, el intérprete de Python sale; no se imprime el seguimiento de pila. El constructor acepta el mismo argumento opcional pasado a <a class="reference internal" href="sys.html#sys.exit" title="sys.exit"><code class="xref py py-func docutils literal notranslate"><span class="pre">sys.exit()</span></code></a>. Si el valor es un entero, especifica el estado de salida del sistema (se pasa a la función <code class="xref c c-func docutils literal notranslate"><span class="pre">exit()</span></code> de C); si es <code class="docutils literal notranslate"><span class="pre">None</span></code>, el estado de salida es cero; Si tiene otro tipo (como una cadena), se imprime el valor del objeto y el estado de salida es uno.</p>
<p>Una llamada <a class="reference internal" href="sys.html#sys.exit" title="sys.exit"><code class="xref py py-func docutils literal notranslate"><span class="pre">sys.exit()</span></code></a> se traduce en una excepción para que los gestores de limpieza (<a class="reference internal" href="../reference/compound_stmts.html#finally"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">finally</span></code></a> cláusulas de <a class="reference internal" href="../reference/compound_stmts.html#try"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">try</span></code></a>) puedan ejecutarse, y para que un depurador pueda ejecutar un <em>script</em> sin correr el riesgo de perder el control. La función <a class="reference internal" href="os.html#os._exit" title="os._exit"><code class="xref py py-func docutils literal notranslate"><span class="pre">os._exit()</span></code></a> se puede usar si es absolutamente necesario salir (por ejemplo, en el proceso secundario después de una llamada a <a class="reference internal" href="os.html#os.fork" title="os.fork"><code class="xref py py-func docutils literal notranslate"><span class="pre">os.fork()</span></code></a>).</p>
<dl class="py attribute">
<dt class="sig sig-object py" id="SystemExit.code">
<span class="sig-name descname"><span class="pre">code</span></span><a class="headerlink" href="#SystemExit.code" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>El estado de salida o mensaje de error que se pasa al constructor. (El valor predeterminado es <code class="docutils literal notranslate"><span class="pre">None</span></code>.)</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="TypeError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">TypeError</span></span><a class="headerlink" href="#TypeError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando una operación o función se aplica a un objeto de tipo inapropiado. El valor asociado es una cadena que proporciona detalles sobre la falta de coincidencia de tipos.</p>
<p>El código de usuario puede lanzar esta excepción para indicar que un intento de operación en un objeto no es compatible y no debe serlo. Si un objeto está destinado a soportar una operación dada pero aún no ha proporcionado una implementación, <a class="reference internal" href="#NotImplementedError" title="NotImplementedError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">NotImplementedError</span></code></a> es la excepción adecuada para lanzar.</p>
<p>Pasar argumentos del tipo incorrecto (por ejemplo, pasar a <a class="reference internal" href="stdtypes.html#list" title="list"><code class="xref py py-class docutils literal notranslate"><span class="pre">list</span></code></a> cuando se espera un <a class="reference internal" href="functions.html#int" title="int"><code class="xref py py-class docutils literal notranslate"><span class="pre">int</span></code></a>) debería dar como resultado <a class="reference internal" href="#TypeError" title="TypeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">TypeError</span></code></a>, pero pasar argumentos con el valor incorrecto (por ejemplo, un número fuera límites esperados) debería dar como resultado <a class="reference internal" href="#ValueError" title="ValueError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ValueError</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="UnboundLocalError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">UnboundLocalError</span></span><a class="headerlink" href="#UnboundLocalError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando se hace referencia a una variable local en una función o método, pero no se ha vinculado ningún valor a esa variable. Esta es una subclase de <a class="reference internal" href="#NameError" title="NameError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">NameError</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="UnicodeError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">UnicodeError</span></span><a class="headerlink" href="#UnicodeError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando se produce un error de codificación o decodificación relacionado con Unicode. Es una subclase de <a class="reference internal" href="#ValueError" title="ValueError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ValueError</span></code></a>.</p>
<p><a class="reference internal" href="#UnicodeError" title="UnicodeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">UnicodeError</span></code></a> tiene atributos que describen el error de codificación o decodificación. Por ejemplo, <code class="docutils literal notranslate"><span class="pre">err.object[err.start:err.end]</span></code> proporciona la entrada inválida particular en la que falló el códec.</p>
<dl class="py attribute">
<dt class="sig sig-object py" id="UnicodeError.encoding">
<span class="sig-name descname"><span class="pre">encoding</span></span><a class="headerlink" href="#UnicodeError.encoding" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>El nombre de la codificación que provocó el error.</p>
</dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="UnicodeError.reason">
<span class="sig-name descname"><span class="pre">reason</span></span><a class="headerlink" href="#UnicodeError.reason" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Una cadena que describe el error de códec específico.</p>
</dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="UnicodeError.object">
<span class="sig-name descname"><span class="pre">object</span></span><a class="headerlink" href="#UnicodeError.object" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>El objeto que el códec intentaba codificar o decodificar.</p>
</dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="UnicodeError.start">
<span class="sig-name descname"><span class="pre">start</span></span><a class="headerlink" href="#UnicodeError.start" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>El primer índice de datos no válidos en <a class="reference internal" href="functions.html#object" title="object"><code class="xref py py-attr docutils literal notranslate"><span class="pre">object</span></code></a>.</p>
</dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="UnicodeError.end">
<span class="sig-name descname"><span class="pre">end</span></span><a class="headerlink" href="#UnicodeError.end" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>El índice después de los últimos datos no válidos en <a class="reference internal" href="functions.html#object" title="object"><code class="xref py py-attr docutils literal notranslate"><span class="pre">object</span></code></a>.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="UnicodeEncodeError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">UnicodeEncodeError</span></span><a class="headerlink" href="#UnicodeEncodeError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando se produce un error relacionado con Unicode durante la codificación. Es una subclase de <a class="reference internal" href="#UnicodeError" title="UnicodeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">UnicodeError</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="UnicodeDecodeError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">UnicodeDecodeError</span></span><a class="headerlink" href="#UnicodeDecodeError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando se produce un error relacionado con Unicode durante la codificación. Es una subclase de <a class="reference internal" href="#UnicodeError" title="UnicodeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">UnicodeError</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="UnicodeTranslateError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">UnicodeTranslateError</span></span><a class="headerlink" href="#UnicodeTranslateError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando se produce un error relacionado con Unicode durante la codificación. Es una subclase de <a class="reference internal" href="#UnicodeError" title="UnicodeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">UnicodeError</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="ValueError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">ValueError</span></span><a class="headerlink" href="#ValueError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando una operación o función recibe un argumento que tiene el tipo correcto pero un valor inapropiado, y la situación no se describe con una excepción más precisa como <a class="reference internal" href="#IndexError" title="IndexError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">IndexError</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="ZeroDivisionError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">ZeroDivisionError</span></span><a class="headerlink" href="#ZeroDivisionError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando el segundo argumento de una operación de división o módulo es cero. El valor asociado es una cadena que indica el tipo de operandos y la operación.</p>
</dd></dl>

<p>Las siguientes excepciones se mantienen por compatibilidad con versiones anteriores; a partir de Python 3.3, son alias de <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">OSError</span></code></a>.</p>
<dl class="py exception">
<dt class="sig sig-object py" id="EnvironmentError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">EnvironmentError</span></span><a class="headerlink" href="#EnvironmentError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd></dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="IOError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">IOError</span></span><a class="headerlink" href="#IOError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd></dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="WindowsError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">WindowsError</span></span><a class="headerlink" href="#WindowsError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Solo disponible en Windows.</p>
</dd></dl>

<section id="os-exceptions">
<h3>Excepciones del sistema operativo<a class="headerlink" href="#os-exceptions" title="Enlazar permanentemente con este título">¶</a></h3>
<p>Las siguientes excepciones son subclases de <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">OSError</span></code></a>, se generan según el código de error del sistema.</p>
<dl class="py exception">
<dt class="sig sig-object py" id="BlockingIOError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">BlockingIOError</span></span><a class="headerlink" href="#BlockingIOError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se lanza cuando una operación se bloquearía en un objeto (ejemplo: socket) configurado para una operación no bloqueante. Corresponde a <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.EAGAIN" title="errno.EAGAIN"><code class="xref py py-data docutils literal notranslate"><span class="pre">EAGAIN</span></code></a>, <a class="reference internal" href="errno.html#errno.EALREADY" title="errno.EALREADY"><code class="xref py py-data docutils literal notranslate"><span class="pre">EALREADY</span></code></a>, <a class="reference internal" href="errno.html#errno.EWOULDBLOCK" title="errno.EWOULDBLOCK"><code class="xref py py-data docutils literal notranslate"><span class="pre">EWOULDBLOCK</span></code></a> y <a class="reference internal" href="errno.html#errno.EINPROGRESS" title="errno.EINPROGRESS"><code class="xref py py-data docutils literal notranslate"><span class="pre">EINPROGRESS</span></code></a>.</p>
<p>Además de los de <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">OSError</span></code></a>, <a class="reference internal" href="#BlockingIOError" title="BlockingIOError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">BlockingIOError</span></code></a> puede tener un atributo más:</p>
<dl class="py attribute">
<dt class="sig sig-object py" id="BlockingIOError.characters_written">
<span class="sig-name descname"><span class="pre">characters_written</span></span><a class="headerlink" href="#BlockingIOError.characters_written" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Un entero que contiene el número de caracteres escritos en la secuencia antes de que se bloquee. Este atributo está disponible cuando se utilizan las clases de E/S almacenadas en el modulo <a class="reference internal" href="io.html#module-io" title="io: Core tools for working with streams."><code class="xref py py-mod docutils literal notranslate"><span class="pre">io</span></code></a>.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="ChildProcessError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">ChildProcessError</span></span><a class="headerlink" href="#ChildProcessError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando falla una operación en un proceso secundario. Corresponde a <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.ECHILD" title="errno.ECHILD"><code class="xref py py-data docutils literal notranslate"><span class="pre">ECHILD</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="ConnectionError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">ConnectionError</span></span><a class="headerlink" href="#ConnectionError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Una clase base para problemas relacionados con la conexión.</p>
<p>Las subclases son <a class="reference internal" href="#BrokenPipeError" title="BrokenPipeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">BrokenPipeError</span></code></a>, <a class="reference internal" href="#ConnectionAbortedError" title="ConnectionAbortedError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ConnectionAbortedError</span></code></a>, <a class="reference internal" href="#ConnectionRefusedError" title="ConnectionRefusedError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ConnectionRefusedError</span></code></a> y <a class="reference internal" href="#ConnectionResetError" title="ConnectionResetError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ConnectionResetError</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="BrokenPipeError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">BrokenPipeError</span></span><a class="headerlink" href="#BrokenPipeError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Una subclase de <a class="reference internal" href="#ConnectionError" title="ConnectionError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ConnectionError</span></code></a>, que se genera cuando se intenta escribir en una tubería mientras el otro extremo se ha cerrado, o cuando se intenta escribir en un <em>socket</em> que se ha cerrado por escritura. Corresponde a <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.EPIPE" title="errno.EPIPE"><code class="xref py py-data docutils literal notranslate"><span class="pre">EPIPE</span></code></a> y <a class="reference internal" href="errno.html#errno.ESHUTDOWN" title="errno.ESHUTDOWN"><code class="xref py py-data docutils literal notranslate"><span class="pre">ESHUTDOWN</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="ConnectionAbortedError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">ConnectionAbortedError</span></span><a class="headerlink" href="#ConnectionAbortedError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Una subclase de <a class="reference internal" href="#ConnectionError" title="ConnectionError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ConnectionError</span></code></a>, que se genera cuando el par interrumpe un intento de conexión. Corresponde a <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.ECONNABORTED" title="errno.ECONNABORTED"><code class="xref py py-data docutils literal notranslate"><span class="pre">ECONNABORTED</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="ConnectionRefusedError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">ConnectionRefusedError</span></span><a class="headerlink" href="#ConnectionRefusedError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Una subclase de <a class="reference internal" href="#ConnectionError" title="ConnectionError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ConnectionError</span></code></a>, que se genera cuando el par interrumpe un intento de conexión. Corresponde a <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.ECONNREFUSED" title="errno.ECONNREFUSED"><code class="xref py py-data docutils literal notranslate"><span class="pre">ECONNREFUSED</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="ConnectionResetError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">ConnectionResetError</span></span><a class="headerlink" href="#ConnectionResetError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Una subclase de <a class="reference internal" href="#ConnectionError" title="ConnectionError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ConnectionError</span></code></a>, que se genera cuando el par restablece una conexión. Corresponde a <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.ECONNRESET" title="errno.ECONNRESET"><code class="xref py py-data docutils literal notranslate"><span class="pre">ECONNRESET</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="FileExistsError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">FileExistsError</span></span><a class="headerlink" href="#FileExistsError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera al intentar crear un archivo o directorio que ya existe. Corresponde a <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.EEXIST" title="errno.EEXIST"><code class="xref py py-data docutils literal notranslate"><span class="pre">EEXIST</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="FileNotFoundError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">FileNotFoundError</span></span><a class="headerlink" href="#FileNotFoundError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando se solicita un archivo o directorio pero no existe. Corresponde a <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.ENOENT" title="errno.ENOENT"><code class="xref py py-data docutils literal notranslate"><span class="pre">ENOENT</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="InterruptedError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">InterruptedError</span></span><a class="headerlink" href="#InterruptedError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando una llamada entrante interrumpe una llamada del sistema. Corresponde a <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.EINTR" title="errno.EINTR"><code class="xref py py-data docutils literal notranslate"><span class="pre">EINTR</span></code></a>.</p>
<div class="versionchanged">
<p><span class="versionmodified changed">Distinto en la versión 3.5: </span>Python ahora vuelve a intentar las llamadas del sistema cuando una señal interrumpe un <em>syscall</em>, excepto si el gestor de señales lanza una excepción (ver <span class="target" id="index-23"></span><a class="pep reference external" href="https://peps.python.org/pep-0475/"><strong>PEP 475</strong></a> para la justificación), en lugar de lanzar <a class="reference internal" href="#InterruptedError" title="InterruptedError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">InterruptedError</span></code></a>.</p>
</div>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="IsADirectoryError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">IsADirectoryError</span></span><a class="headerlink" href="#IsADirectoryError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando se solicita una operación de archivo (como <a class="reference internal" href="os.html#os.remove" title="os.remove"><code class="xref py py-func docutils literal notranslate"><span class="pre">os.remove()</span></code></a>) en un directorio. Corresponde a: <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.EISDIR" title="errno.EISDIR"><code class="xref py py-data docutils literal notranslate"><span class="pre">EISDIR</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="NotADirectoryError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">NotADirectoryError</span></span><a class="headerlink" href="#NotADirectoryError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando se solicita una operación de directorio (como <a class="reference internal" href="os.html#os.listdir" title="os.listdir"><code class="xref py py-func docutils literal notranslate"><span class="pre">os.listdir()</span></code></a>) en algo que no es un directorio.  En la mayoría de las plataformas POSIX, también se puede lanzar si una operación intenta abrir o recorrer un archivo que no es de directorio como si fuera un directorio. Corresponde a <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.ENOTDIR" title="errno.ENOTDIR"><code class="xref py py-data docutils literal notranslate"><span class="pre">ENOTDIR</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="PermissionError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">PermissionError</span></span><a class="headerlink" href="#PermissionError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando se intenta ejecutar una operación sin los permisos de acceso adecuados - por ejemplo permisos del sistema de archivos. Corresponde a <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.EACCES" title="errno.EACCES"><code class="xref py py-data docutils literal notranslate"><span class="pre">EACCES</span></code></a>, <a class="reference internal" href="errno.html#errno.EPERM" title="errno.EPERM"><code class="xref py py-data docutils literal notranslate"><span class="pre">EPERM</span></code></a>, y <a class="reference internal" href="errno.html#errno.ENOTCAPABLE" title="errno.ENOTCAPABLE"><code class="xref py py-data docutils literal notranslate"><span class="pre">ENOTCAPABLE</span></code></a>.</p>
<div class="versionchanged">
<p><span class="versionmodified changed">Distinto en la versión 3.11.1: </span>WASI’s <a class="reference internal" href="errno.html#errno.ENOTCAPABLE" title="errno.ENOTCAPABLE"><code class="xref py py-data docutils literal notranslate"><span class="pre">ENOTCAPABLE</span></code></a> ahora se mapea a <a class="reference internal" href="#PermissionError" title="PermissionError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">PermissionError</span></code></a>.</p>
</div>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="ProcessLookupError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">ProcessLookupError</span></span><a class="headerlink" href="#ProcessLookupError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Generado cuando un proceso dado no existe. Corresponde a <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.ESRCH" title="errno.ESRCH"><code class="xref py py-data docutils literal notranslate"><span class="pre">ESRCH</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="TimeoutError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">TimeoutError</span></span><a class="headerlink" href="#TimeoutError" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Se genera cuando se agota el tiempo de espera de una función del sistema a nivel del sistema. Corresponde a <code class="xref c c-data docutils literal notranslate"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.ETIMEDOUT" title="errno.ETIMEDOUT"><code class="xref py py-data docutils literal notranslate"><span class="pre">ETIMEDOUT</span></code></a>.</p>
</dd></dl>

<div class="versionadded">
<p><span class="versionmodified added">Nuevo en la versión 3.3: </span>Por lo anterior se agregaron las subclases <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">OSError</span></code></a>.</p>
</div>
<div class="admonition seealso">
<p class="admonition-title">Ver también</p>
<p><span class="target" id="index-24"></span><a class="pep reference external" href="https://peps.python.org/pep-3151/"><strong>PEP 3151</strong></a> - Reelaborando el sistema operativo y la jerarquía de excepciones E/S</p>
</div>
</section>
</section>
<section id="warnings">
<span id="warning-categories-as-exceptions"></span><h2>Advertencias<a class="headerlink" href="#warnings" title="Enlazar permanentemente con este título">¶</a></h2>
<p>Las siguientes excepciones se utilizan como categorías de advertencia; consulte la documentación de <a class="reference internal" href="warnings.html#warning-categories"><span class="std std-ref">Categorías de advertencia</span></a> para obtener más detalles.</p>
<dl class="py exception">
<dt class="sig sig-object py" id="Warning">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">Warning</span></span><a class="headerlink" href="#Warning" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Clase base para categorías de advertencia.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="UserWarning">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">UserWarning</span></span><a class="headerlink" href="#UserWarning" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Clase base para advertencias generadas por código de usuario.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="DeprecationWarning">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">DeprecationWarning</span></span><a class="headerlink" href="#DeprecationWarning" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Clase base para advertencias sobre características obsoletas cuando esas advertencias están destinadas a otros desarrolladores de Python.</p>
<p>Ignorado por los filtros de advertencia predeterminados, excepto en el módulo <code class="docutils literal notranslate"><span class="pre">__main__</span></code> (<span class="target" id="index-25"></span><a class="pep reference external" href="https://peps.python.org/pep-0565/"><strong>PEP 565</strong></a>). Habilitando <a class="reference internal" href="devmode.html#devmode"><span class="std std-ref">Modo Desarrollo de Python</span></a> muestra esta advertencia.</p>
<p>La política de obsolescencia se describe en <span class="target" id="index-26"></span><a class="pep reference external" href="https://peps.python.org/pep-0387/"><strong>PEP 387</strong></a>.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="PendingDeprecationWarning">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">PendingDeprecationWarning</span></span><a class="headerlink" href="#PendingDeprecationWarning" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Clase base para advertencias sobre características que están obsoletas y que se espera que sean obsoletas en el futuro, pero que no lo son en este momento.</p>
<p>Esta clase rara vez se usa para emitir una advertencia sobre una posible desaprobación próxima es inusual, y <a class="reference internal" href="#DeprecationWarning" title="DeprecationWarning"><code class="xref py py-exc docutils literal notranslate"><span class="pre">DeprecationWarning</span></code></a> se prefiere para las desaprobaciones ya activas.</p>
<p>Ignorado por los filtros de advertencia predeterminados. Habilitando <a class="reference internal" href="devmode.html#devmode"><span class="std std-ref">Modo Desarrollo de Python</span></a> muestra esta advertencia.</p>
<p>La política de obsolescencia se describe en <span class="target" id="index-27"></span><a class="pep reference external" href="https://peps.python.org/pep-0387/"><strong>PEP 387</strong></a>.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="SyntaxWarning">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">SyntaxWarning</span></span><a class="headerlink" href="#SyntaxWarning" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Clase base para advertencias sobre sintaxis dudosa.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="RuntimeWarning">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">RuntimeWarning</span></span><a class="headerlink" href="#RuntimeWarning" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Clase base para advertencias sobre comportamiento dudoso en tiempo de ejecución.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="FutureWarning">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">FutureWarning</span></span><a class="headerlink" href="#FutureWarning" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Clase base para advertencias sobre características en desuso cuando esas advertencias están destinadas a usuarios finales de aplicaciones escritas en Python.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="ImportWarning">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">ImportWarning</span></span><a class="headerlink" href="#ImportWarning" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Clase base para advertencias sobre posibles errores en la importación de módulos.</p>
<p>Ignorado por los filtros de advertencia predeterminados. Habilitando <a class="reference internal" href="devmode.html#devmode"><span class="std std-ref">Modo Desarrollo de Python</span></a> muestra esta advertencia.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="UnicodeWarning">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">UnicodeWarning</span></span><a class="headerlink" href="#UnicodeWarning" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Clase base para advertencias relacionadas con Unicode.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="EncodingWarning">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">EncodingWarning</span></span><a class="headerlink" href="#EncodingWarning" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Clase base para advertencias relacionadas con codificaciones.</p>
<p>Consulte <a class="reference internal" href="io.html#io-encoding-warning"><span class="std std-ref">EncodingWarning opcional</span></a> para obtener más detalles.</p>
<div class="versionadded">
<p><span class="versionmodified added">Nuevo en la versión 3.10.</span></p>
</div>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="BytesWarning">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">BytesWarning</span></span><a class="headerlink" href="#BytesWarning" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Clase base para advertencias relacionadas con <a class="reference internal" href="stdtypes.html#bytes" title="bytes"><code class="xref py py-class docutils literal notranslate"><span class="pre">bytes</span></code></a> y <a class="reference internal" href="stdtypes.html#bytearray" title="bytearray"><code class="xref py py-class docutils literal notranslate"><span class="pre">bytearray</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="ResourceWarning">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">ResourceWarning</span></span><a class="headerlink" href="#ResourceWarning" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Clase base para advertencias relacionadas con el uso de recursos.</p>
<p>Ignorado por los filtros de advertencia predeterminados. Habilitando <a class="reference internal" href="devmode.html#devmode"><span class="std std-ref">Modo Desarrollo de Python</span></a> muestra esta advertencia.</p>
<div class="versionadded">
<p><span class="versionmodified added">Nuevo en la versión 3.2.</span></p>
</div>
</dd></dl>

</section>
<section id="exception-groups">
<h2>Grupos de excepciones<a class="headerlink" href="#exception-groups" title="Enlazar permanentemente con este título">¶</a></h2>
<p>Las siguientes se utilizan cuando es necesario lanzar múltiples excepciones no relacionadas. Forman parte de la jerarquía de excepciones, por lo que pueden ser manejadas con <a class="reference internal" href="../reference/compound_stmts.html#except"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">except</span></code></a> como todas las demás excepciones. Además, son reconocidas por <a class="reference internal" href="../reference/compound_stmts.html#except-star"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">except*</span></code></a>, lo que hace coincidir sus subgrupos basándose en los tipos de las excepciones contenidas.</p>
<dl class="py exception">
<dt class="sig sig-object py" id="ExceptionGroup">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">ExceptionGroup</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">msg</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">excs</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#ExceptionGroup" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd></dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="BaseExceptionGroup">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">BaseExceptionGroup</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">msg</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">excs</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#BaseExceptionGroup" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Ambos tipos de excepción envuelven las excepciones en la secuencia <code class="docutils literal notranslate"><span class="pre">excs</span></code>. El parámetro <code class="docutils literal notranslate"><span class="pre">msg</span></code> debe ser una cadena de caracteres. La diferencia entre las dos clases es que <a class="reference internal" href="#BaseExceptionGroup" title="BaseExceptionGroup"><code class="xref py py-exc docutils literal notranslate"><span class="pre">BaseExceptionGroup</span></code></a> extiende a <a class="reference internal" href="#BaseException" title="BaseException"><code class="xref py py-exc docutils literal notranslate"><span class="pre">BaseException</span></code></a> y puede envolver cualquier excepción, mientras que <a class="reference internal" href="#ExceptionGroup" title="ExceptionGroup"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ExceptionGroup</span></code></a> extiende a <a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal notranslate"><span class="pre">Exception</span></code></a> y solo puede envolver subclases de <a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal notranslate"><span class="pre">Exception</span></code></a>. Este diseño está pensado para que <code class="docutils literal notranslate"><span class="pre">except</span> <span class="pre">Exception</span></code> capture un <a class="reference internal" href="#ExceptionGroup" title="ExceptionGroup"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ExceptionGroup</span></code></a> pero no <a class="reference internal" href="#BaseExceptionGroup" title="BaseExceptionGroup"><code class="xref py py-exc docutils literal notranslate"><span class="pre">BaseExceptionGroup</span></code></a></p>
<p>El constructor <a class="reference internal" href="#BaseExceptionGroup" title="BaseExceptionGroup"><code class="xref py py-exc docutils literal notranslate"><span class="pre">BaseExceptionGroup</span></code></a> retorna una <a class="reference internal" href="#ExceptionGroup" title="ExceptionGroup"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ExceptionGroup</span></code></a> en lugar de una <a class="reference internal" href="#BaseExceptionGroup" title="BaseExceptionGroup"><code class="xref py py-exc docutils literal notranslate"><span class="pre">BaseExceptionGroup</span></code></a> si todas las excepciones contenidas son instancias de <a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal notranslate"><span class="pre">Exception</span></code></a> , por lo que puede utilizarse para hacer la selección automática. El constructor <a class="reference internal" href="#ExceptionGroup" title="ExceptionGroup"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ExceptionGroup</span></code></a>, por su parte, lanza un <a class="reference internal" href="#TypeError" title="TypeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">TypeError</span></code></a> si alguna de las excepciones contenidas no es una subclase de <a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal notranslate"><span class="pre">Exception</span></code></a>.</p>
<dl class="py attribute">
<dt class="sig sig-object py" id="BaseExceptionGroup.message">
<span class="sig-name descname"><span class="pre">message</span></span><a class="headerlink" href="#BaseExceptionGroup.message" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>El argumento <code class="docutils literal notranslate"><span class="pre">msg</span></code> para el constructor. Este atributo es de sólo lectura.</p>
</dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="BaseExceptionGroup.exceptions">
<span class="sig-name descname"><span class="pre">exceptions</span></span><a class="headerlink" href="#BaseExceptionGroup.exceptions" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Una tupla de la excepciones en la secuencia <code class="docutils literal notranslate"><span class="pre">excs</span></code> pasada al constructor. Este atributo es de sólo lectura.</p>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="BaseExceptionGroup.subgroup">
<span class="sig-name descname"><span class="pre">subgroup</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">condition</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#BaseExceptionGroup.subgroup" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Retorna un grupo de excepciones que contiene sólo las excepciones del grupo actual que cumplen con <em>condition</em>, o <code class="docutils literal notranslate"><span class="pre">None</span></code> si el resultado está vacío.</p>
<p>La condición puede ser una función que acepta una excepción y retorna <em>True</em> para aquellas que deberían estar en el subgrupo, o puede ser un tipo de excepción o una tupla de tipos de excepción, que se utiliza para comprobar una coincidencia utilizando la misma comprobación que se utiliza en una cláusula <code class="docutils literal notranslate"><span class="pre">except</span></code>.</p>
<p>La estructura de anidamiento de la excepción actual se conserva en el resultado, así como también los valores de sus campos <a class="reference internal" href="#BaseExceptionGroup.message" title="BaseExceptionGroup.message"><code class="xref py py-attr docutils literal notranslate"><span class="pre">message</span></code></a>, <code class="xref py py-attr docutils literal notranslate"><span class="pre">__traceback__</span></code>, <code class="xref py py-attr docutils literal notranslate"><span class="pre">__cause__</span></code>, <code class="xref py py-attr docutils literal notranslate"><span class="pre">__context__</span></code> y <code class="xref py py-attr docutils literal notranslate"><span class="pre">__notes__</span></code>. Los grupos anidados vacíos son omitidos del resultado.</p>
<p>La condición se comprueba para todas las excepciones del grupo de excepción anidado, incluyendo el nivel superior y cualquier grupo de excepción anidado. Si la condición es verdadera para dicho grupo de excepción, se incluye en el resultado en su totalidad.</p>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="BaseExceptionGroup.split">
<span class="sig-name descname"><span class="pre">split</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">condition</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#BaseExceptionGroup.split" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Al igual que <a class="reference internal" href="#BaseExceptionGroup.subgroup" title="BaseExceptionGroup.subgroup"><code class="xref py py-meth docutils literal notranslate"><span class="pre">subgroup()</span></code></a>, pero retorna el par <code class="docutils literal notranslate"><span class="pre">(match,</span> <span class="pre">rest)</span></code> donde <code class="docutils literal notranslate"><span class="pre">match</span></code> es <code class="docutils literal notranslate"><span class="pre">subgroup(condition)</span></code> y <code class="docutils literal notranslate"><span class="pre">rest</span></code> es la parte restante que no coincide.</p>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="BaseExceptionGroup.derive">
<span class="sig-name descname"><span class="pre">derive</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">excs</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#BaseExceptionGroup.derive" title="Enlazar permanentemente con esta definición">¶</a></dt>
<dd><p>Returns an exception group with the same <a class="reference internal" href="#BaseExceptionGroup.message" title="BaseExceptionGroup.message"><code class="xref py py-attr docutils literal notranslate"><span class="pre">message</span></code></a>, but which
wraps the exceptions in <code class="docutils literal notranslate"><span class="pre">excs</span></code>.</p>
<p>This method is used by <a class="reference internal" href="#BaseExceptionGroup.subgroup" title="BaseExceptionGroup.subgroup"><code class="xref py py-meth docutils literal notranslate"><span class="pre">subgroup()</span></code></a> and <a class="reference internal" href="#BaseExceptionGroup.split" title="BaseExceptionGroup.split"><code class="xref py py-meth docutils literal notranslate"><span class="pre">split()</span></code></a>. A
subclass needs to override it in order to make <a class="reference internal" href="#BaseExceptionGroup.subgroup" title="BaseExceptionGroup.subgroup"><code class="xref py py-meth docutils literal notranslate"><span class="pre">subgroup()</span></code></a>
and <a class="reference internal" href="#BaseExceptionGroup.split" title="BaseExceptionGroup.split"><code class="xref py py-meth docutils literal notranslate"><span class="pre">split()</span></code></a> return instances of the subclass rather
than <a class="reference internal" href="#ExceptionGroup" title="ExceptionGroup"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ExceptionGroup</span></code></a>.</p>
<p><a class="reference internal" href="#BaseExceptionGroup.subgroup" title="BaseExceptionGroup.subgroup"><code class="xref py py-meth docutils literal notranslate"><span class="pre">subgroup()</span></code></a> and <a class="reference internal" href="#BaseExceptionGroup.split" title="BaseExceptionGroup.split"><code class="xref py py-meth docutils literal notranslate"><span class="pre">split()</span></code></a> copy the <code class="xref py py-attr docutils literal notranslate"><span class="pre">__traceback__</span></code>,
<code class="xref py py-attr docutils literal notranslate"><span class="pre">__cause__</span></code>, <code class="xref py py-attr docutils literal notranslate"><span class="pre">__context__</span></code> and <code class="xref py py-attr docutils literal notranslate"><span class="pre">__notes__</span></code> fields from
the original exception group to the one returned by <a class="reference internal" href="#BaseExceptionGroup.derive" title="BaseExceptionGroup.derive"><code class="xref py py-meth docutils literal notranslate"><span class="pre">derive()</span></code></a>, so
these fields do not need to be updated by <a class="reference internal" href="#BaseExceptionGroup.derive" title="BaseExceptionGroup.derive"><code class="xref py py-meth docutils literal notranslate"><span class="pre">derive()</span></code></a>.</p>
<div class="highlight-python3 notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">class</span> <span class="nc">MyGroup</span><span class="p">(</span><span class="n">ExceptionGroup</span><span class="p">):</span>
<span class="gp">... </span>    <span class="k">def</span> <span class="nf">derive</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">excs</span><span class="p">):</span>
<span class="gp">... </span>        <span class="k">return</span> <span class="n">MyGroup</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">message</span><span class="p">,</span> <span class="n">excs</span><span class="p">)</span>
<span class="gp">...</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">e</span> <span class="o">=</span> <span class="n">MyGroup</span><span class="p">(</span><span class="s2">&quot;eg&quot;</span><span class="p">,</span> <span class="p">[</span><span class="ne">ValueError</span><span class="p">(</span><span class="mi">1</span><span class="p">),</span> <span class="ne">TypeError</span><span class="p">(</span><span class="mi">2</span><span class="p">)])</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">e</span><span class="o">.</span><span class="n">add_note</span><span class="p">(</span><span class="s2">&quot;a note&quot;</span><span class="p">)</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">e</span><span class="o">.</span><span class="n">__context__</span> <span class="o">=</span> <span class="ne">Exception</span><span class="p">(</span><span class="s2">&quot;context&quot;</span><span class="p">)</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">e</span><span class="o">.</span><span class="n">__cause__</span> <span class="o">=</span> <span class="ne">Exception</span><span class="p">(</span><span class="s2">&quot;cause&quot;</span><span class="p">)</span>
<span class="gp">&gt;&gt;&gt; </span><span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>   <span class="k">raise</span> <span class="n">e</span>
<span class="gp">... </span><span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
<span class="gp">... </span>   <span class="n">exc</span> <span class="o">=</span> <span class="n">e</span>
<span class="gp">...</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">match</span><span class="p">,</span> <span class="n">rest</span> <span class="o">=</span> <span class="n">exc</span><span class="o">.</span><span class="n">split</span><span class="p">(</span><span class="ne">ValueError</span><span class="p">)</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">exc</span><span class="p">,</span> <span class="n">exc</span><span class="o">.</span><span class="n">__context__</span><span class="p">,</span> <span class="n">exc</span><span class="o">.</span><span class="n">__cause__</span><span class="p">,</span> <span class="n">exc</span><span class="o">.</span><span class="n">__notes__</span>
<span class="go">(MyGroup(&#39;eg&#39;, [ValueError(1), TypeError(2)]), Exception(&#39;context&#39;), Exception(&#39;cause&#39;), [&#39;a note&#39;])</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">match</span><span class="p">,</span> <span class="n">match</span><span class="o">.</span><span class="n">__context__</span><span class="p">,</span> <span class="n">match</span><span class="o">.</span><span class="n">__cause__</span><span class="p">,</span> <span class="n">match</span><span class="o">.</span><span class="n">__notes__</span>
<span class="go">(MyGroup(&#39;eg&#39;, [ValueError(1)]), Exception(&#39;context&#39;), Exception(&#39;cause&#39;), [&#39;a note&#39;])</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">rest</span><span class="p">,</span> <span class="n">rest</span><span class="o">.</span><span class="n">__context__</span><span class="p">,</span> <span class="n">rest</span><span class="o">.</span><span class="n">__cause__</span><span class="p">,</span> <span class="n">rest</span><span class="o">.</span><span class="n">__notes__</span>
<span class="go">(MyGroup(&#39;eg&#39;, [TypeError(2)]), Exception(&#39;context&#39;), Exception(&#39;cause&#39;), [&#39;a note&#39;])</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">exc</span><span class="o">.</span><span class="n">__traceback__</span> <span class="ow">is</span> <span class="n">match</span><span class="o">.</span><span class="n">__traceback__</span> <span class="ow">is</span> <span class="n">rest</span><span class="o">.</span><span class="n">__traceback__</span>
<span class="go">True</span>
</pre></div>
</div>
</dd></dl>

<p>Note that <a class="reference internal" href="#BaseExceptionGroup" title="BaseExceptionGroup"><code class="xref py py-exc docutils literal notranslate"><span class="pre">BaseExceptionGroup</span></code></a> defines <code class="xref py py-meth docutils literal notranslate"><span class="pre">__new__()</span></code>, so
subclasses that need a different constructor signature need to
override that rather than <code class="xref py py-meth docutils literal notranslate"><span class="pre">__init__()</span></code>. For example, the following
defines an exception group subclass which accepts an exit_code and
and constructs the group’s message from it.</p>
<div class="highlight-python3 notranslate"><div class="highlight"><pre><span></span><span class="k">class</span> <span class="nc">Errors</span><span class="p">(</span><span class="n">ExceptionGroup</span><span class="p">):</span>
   <span class="k">def</span> <span class="fm">__new__</span><span class="p">(</span><span class="bp">cls</span><span class="p">,</span> <span class="n">errors</span><span class="p">,</span> <span class="n">exit_code</span><span class="p">):</span>
      <span class="bp">self</span> <span class="o">=</span> <span class="nb">super</span><span class="p">()</span><span class="o">.</span><span class="fm">__new__</span><span class="p">(</span><span class="n">Errors</span><span class="p">,</span> <span class="sa">f</span><span class="s2">&quot;exit code: </span><span class="si">{</span><span class="n">exit_code</span><span class="si">}</span><span class="s2">&quot;</span><span class="p">,</span> <span class="n">errors</span><span class="p">)</span>
      <span class="bp">self</span><span class="o">.</span><span class="n">exit_code</span> <span class="o">=</span> <span class="n">exit_code</span>
      <span class="k">return</span> <span class="bp">self</span>

   <span class="k">def</span> <span class="nf">derive</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">excs</span><span class="p">):</span>
      <span class="k">return</span> <span class="n">Errors</span><span class="p">(</span><span class="n">excs</span><span class="p">,</span> <span class="bp">self</span><span class="o">.</span><span class="n">exit_code</span><span class="p">)</span>
</pre></div>
</div>
<p>Like <a class="reference internal" href="#ExceptionGroup" title="ExceptionGroup"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ExceptionGroup</span></code></a>, any subclass of <a class="reference internal" href="#BaseExceptionGroup" title="BaseExceptionGroup"><code class="xref py py-exc docutils literal notranslate"><span class="pre">BaseExceptionGroup</span></code></a> which
is also a subclass of <a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal notranslate"><span class="pre">Exception</span></code></a> can only wrap instances of
<a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal notranslate"><span class="pre">Exception</span></code></a>.</p>
<div class="versionadded">
<p><span class="versionmodified added">Nuevo en la versión 3.11.</span></p>
</div>
</dd></dl>

</section>
<section id="exception-hierarchy">
<h2>Jerarquía de excepción<a class="headerlink" href="#exception-hierarchy" title="Enlazar permanentemente con este título">¶</a></h2>
<p>La jerarquía de clases para las excepciones incorporadas es:</p>
<div class="highlight-text notranslate"><div class="highlight"><pre><span></span>BaseException
 ├── BaseExceptionGroup
 ├── GeneratorExit
 ├── KeyboardInterrupt
 ├── SystemExit
 └── Exception
      ├── ArithmeticError
      │    ├── FloatingPointError
      │    ├── OverflowError
      │    └── ZeroDivisionError
      ├── AssertionError
      ├── AttributeError
      ├── BufferError
      ├── EOFError
      ├── ExceptionGroup [BaseExceptionGroup]
      ├── ImportError
      │    └── ModuleNotFoundError
      ├── LookupError
      │    ├── IndexError
      │    └── KeyError
      ├── MemoryError
      ├── NameError
      │    └── UnboundLocalError
      ├── OSError
      │    ├── BlockingIOError
      │    ├── ChildProcessError
      │    ├── ConnectionError
      │    │    ├── BrokenPipeError
      │    │    ├── ConnectionAbortedError
      │    │    ├── ConnectionRefusedError
      │    │    └── ConnectionResetError
      │    ├── FileExistsError
      │    ├── FileNotFoundError
      │    ├── InterruptedError
      │    ├── IsADirectoryError
      │    ├── NotADirectoryError
      │    ├── PermissionError
      │    ├── ProcessLookupError
      │    └── TimeoutError
      ├── ReferenceError
      ├── RuntimeError
      │    ├── NotImplementedError
      │    └── RecursionError
      ├── StopAsyncIteration
      ├── StopIteration
      ├── SyntaxError
      │    └── IndentationError
      │         └── TabError
      ├── SystemError
      ├── TypeError
      ├── ValueError
      │    └── UnicodeError
      │         ├── UnicodeDecodeError
      │         ├── UnicodeEncodeError
      │         └── UnicodeTranslateError
      └── Warning
           ├── BytesWarning
           ├── DeprecationWarning
           ├── EncodingWarning
           ├── FutureWarning
           ├── ImportWarning
           ├── PendingDeprecationWarning
           ├── ResourceWarning
           ├── RuntimeWarning
           ├── SyntaxWarning
           ├── UnicodeWarning
           └── UserWarning
</pre></div>
</div>
</section>
</section>


            <div class="clearer"></div>
          </div>
        </div>
      </div>
      <div class="sphinxsidebar" role="navigation" aria-label="main navigation">
        <div class="sphinxsidebarwrapper">
  <div>
    <h3><a href="../contents.html">Tabla de contenido</a></h3>
    <ul>
<li><a class="reference internal" href="#">Excepciones incorporadas</a><ul>
<li><a class="reference internal" href="#exception-context">Contexto de una excepción</a></li>
<li><a class="reference internal" href="#inheriting-from-built-in-exceptions">Heredando de excepciones incorporadas</a></li>
<li><a class="reference internal" href="#base-classes">Clases base</a></li>
<li><a class="reference internal" href="#concrete-exceptions">Excepciones específicas</a><ul>
<li><a class="reference internal" href="#os-exceptions">Excepciones del sistema operativo</a></li>
</ul>
</li>
<li><a class="reference internal" href="#warnings">Advertencias</a></li>
<li><a class="reference internal" href="#exception-groups">Grupos de excepciones</a></li>
<li><a class="reference internal" href="#exception-hierarchy">Jerarquía de excepción</a></li>
</ul>
</li>
</ul>

  </div>
  <div>
    <h4>Tema anterior</h4>
    <p class="topless"><a href="stdtypes.html"
                          title="capítulo anterior">Tipos integrados</a></p>
  </div>
  <div>
    <h4>Próximo tema</h4>
    <p class="topless"><a href="text.html"
                          title="próximo capítulo">Servicios de procesamiento de texto</a></p>
  </div>
  <div role="note" aria-label="source link">
    <h3>Esta página</h3>
    <ul class="this-page-menu">
      <li><a href="../bugs.html">Reporta un bug</a></li>
      <li>
        <a href="https://github.com/python/cpython/blob/3.11/Doc/library/exceptions.rst"
            rel="nofollow">Ver fuente
        </a>
      </li>
    </ul>
  </div>
        </div>
      </div>
      <div class="clearer"></div>
    </div>  
    <div class="related" role="navigation" aria-label="related navigation">
      <h3>Navegación</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="../genindex.html" title="Índice general"
             >índice</a></li>
        <li class="right" >
          <a href="../py-modindex.html" title="Índice de Módulos Python"
             >módulos</a> |</li>
        <li class="right" >
          <a href="text.html" title="Servicios de procesamiento de texto"
             >siguiente</a> |</li>
        <li class="right" >
          <a href="stdtypes.html" title="Tipos integrados"
             >anterior</a> |</li>

          <li><img src="../_static/py.svg" alt="python logo" style="vertical-align: middle; margin-top: -1px"/></li>
          <li><a href="https://www.python.org/">Python</a> &#187;</li>
          <li class="switchers">
            <div class="language_switcher_placeholder"></div>
            <div class="version_switcher_placeholder"></div>
          </li>
          <li>
              
          </li>
    <li id="cpython-language-and-version">
      <a href="../index.html">3.11.2 Documentation</a> &#187;
    </li>

          <li class="nav-item nav-item-1"><a href="index.html" >La biblioteca estándar de Python</a> &#187;</li>
        <li class="nav-item nav-item-this"><a href="">Excepciones incorporadas</a></li>
                <li class="right">
                    

    <div class="inline-search" role="search">
        <form class="inline-search" action="../search.html" method="get">
          <input placeholder="Búsqueda rápida" aria-label="Búsqueda rápida" type="text" name="q" />
          <input type="submit" value="Ir" />
          <input type="hidden" name="check_keywords" value="yes" />
          <input type="hidden" name="area" value="default" />
        </form>
    </div>
                     |
                </li>
            
      </ul>
    </div>  
    <div class="footer">
    &copy; <a href="../copyright.html">Copyright</a> 2001-2023, Python Software Foundation.
    <br />
    This page is licensed under the Python Software Foundation License Version 2.
    <br />
    Examples, recipes, and other code in the documentation are additionally licensed under the Zero Clause BSD License.
    <br />
    See <a href="/license.html">History and License</a> for more information.<br />
    <br />

    La Python Software Foundation es una organización sin fines de lucro.
<a href="https://www.python.org/psf/donations/">Por favor, haga una donación.</a>
<br />
    <br />

    Última actualización el mar 23, 2023.
    <a href="/bugs.html">Found a bug</a>?
    <br />

    Created using <a href="https://www.sphinx-doc.org/">Sphinx</a> 4.5.0.
    </div>

  </body>
</html>